### PR TITLE
Slightly faster search

### PR DESCRIPTION
**Pull request by fiacobelli**
I used regular expressions, to improve speed by about a minute.

### CODE REVIEW

**Comment by Rvkstrauss** [comment]
Hi,
Is there any way we can meet tomorrow? If you'd be willing, I'd like to
keep working toward my presentation.
Also is there any way you can get that generalized reference letter to me?
I'd really like to turn in a couple of job apps..
Thanks!

**Comment by fiacobelli** [comment]
Yes. Can you meet around 2pm?

On Sun, Apr 12, 2015 at 11:08 AM, Rvkstrauss notifications@github.com
wrote:

> Hi,
> Is there any way we can meet tomorrow? If you'd be willing, I'd like to
> keep working toward my presentation.
> Also is there any way you can get that generalized reference letter to me?
> I'd really like to turn in a couple of job apps..
> Thanks!
> On Apr 10, 2015 1:49 PM, "Francisco Iacobelli" notifications@github.com
> wrote:
> 
> > ## I used regular expressions, to improve speed by about a minute.
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/Rvkstrauss/Bioinformatics/pull/1
> > Commit Summary
> > - a bit faster with regexps
> > - using regexps
> > 
> > File Changes
> > - _M_ micro_sats.py
> >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-0
> >   (143)
> > - _A_ test_data/output_dna.tsv
> >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-1
> >   (26996)
> > - _A_ test_data/output_dna2.tsv
> >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-2
> >   (76408)
> > - _A_ test_data/test_dna.fa
> >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-3
> >   (10000)
> > - _A_ test_data/test_small.fa
> >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-4
> >   (10)
> > 
> > Patch Links:
> > - https://github.com/Rvkstrauss/Bioinformatics/pull/1.patch
> > - https://github.com/Rvkstrauss/Bioinformatics/pull/1.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Rvkstrauss/Bioinformatics/pull/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rvkstrauss/Bioinformatics/pull/1#issuecomment-92084058
> .

## 

Francisco Iacobelli, Assistant Professor

Department of Computer Science
Northeastern Illinois University
5500 North St. Louis Avenue, Chicago, IL 60625
Phone: (773) 442 4728
f-iacobelli@neiu.edu
http://fid.cl

www.neiu.edu

**Comment by Rvkstrauss** [comment]
Sure! I'll see you then.
Rivka

**Comment by fiacobelli** [comment]
Perfect.

On Mon, Apr 13, 2015 at 9:04 AM, Rvkstrauss notifications@github.com
wrote:

> Sure! I'll see you then.
> Rivka
> On Apr 13, 2015 9:02 AM, "Francisco Iacobelli" notifications@github.com
> wrote:
> 
> > Yes. Can you meet around 2pm?
> > 
> > On Sun, Apr 12, 2015 at 11:08 AM, Rvkstrauss notifications@github.com
> > wrote:
> > 
> > > Hi,
> > > Is there any way we can meet tomorrow? If you'd be willing, I'd like to
> > > keep working toward my presentation.
> > > Also is there any way you can get that generalized reference letter to
> > > me?
> > > I'd really like to turn in a couple of job apps..
> > > Thanks!
> > > On Apr 10, 2015 1:49 PM, "Francisco Iacobelli" <
> > > notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > ## I used regular expressions, to improve speed by about a minute.
> > > > 
> > > > You can view, comment on, or merge this pull request online at:
> > > > 
> > > > https://github.com/Rvkstrauss/Bioinformatics/pull/1
> > > > Commit Summary
> > > > - a bit faster with regexps
> > > > - using regexps
> > > > 
> > > > File Changes
> > > > - _M_ micro_sats.py
> > > >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-0
> > > >   (143)
> > > > - _A_ test_data/output_dna.tsv
> > > >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-1
> > > >   (26996)
> > > > - _A_ test_data/output_dna2.tsv
> > > >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-2
> > > >   (76408)
> > > > - _A_ test_data/test_dna.fa
> > > >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-3
> > > >   (10000)
> > > > - _A_ test_data/test_small.fa
> > > >   https://github.com/Rvkstrauss/Bioinformatics/pull/1/files#diff-4
> > > >   (10)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/Rvkstrauss/Bioinformatics/pull/1.patch
> > > > - https://github.com/Rvkstrauss/Bioinformatics/pull/1.diff
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/Rvkstrauss/Bioinformatics/pull/1.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Rvkstrauss/Bioinformatics/pull/1#issuecomment-92084058>
> > 
> > > .
> > 
> > ## 
> > 
> > Francisco Iacobelli, Assistant Professor
> > 
> > Department of Computer Science
> > Northeastern Illinois University
> > 5500 North St. Louis Avenue, Chicago, IL 60625
> > Phone: (773) 442 4728
> > f-iacobelli@neiu.edu
> > http://fid.cl
> > 
> > www.neiu.edu
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Rvkstrauss/Bioinformatics/pull/1#issuecomment-92366999>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rvkstrauss/Bioinformatics/pull/1#issuecomment-92367562
> .

## 

Francisco Iacobelli, Assistant Professor

Department of Computer Science
Northeastern Illinois University
5500 North St. Louis Avenue, Chicago, IL 60625
Phone: (773) 442 4728
f-iacobelli@neiu.edu
http://fid.cl

www.neiu.edu

**Pull request merged**
